### ISSUE TITLE
FakeNewsDetect: TODO List

### ISSUE THREAD

**Issue by YoruCathy** [YoruCathy/FakeNewsDetect#1]
- [ ] Get dataset
- [ ] Implement baseline with SVM
- [ ] Implement baseline with NaiveBayes
- [ ] Extract feature from image
- [ ] Extract  feature from text
